server:
  port: 0 # ??? ??? ???? ?? ?? ?? ??

spring:
  application:
    name: user-service
  devtools:
    livereload:
      enabled: false

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}} # instance_id ??? ??? ?? ??
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: # eureka ??? ??? ?? ???? endpoint
      defaultZone: http://127.0.0.1:8761/eureka